### ISSUE TITLE
pure python emulator

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#21]
a pure Python emulation backend to give basic emulation support without installing Julia.

items left to do:

- [x] #532
- [x] #533
- [x] #534
- [x] #555 
- [x] #627

**Comment by weinbe58** [comment]
items left to do:

- [ ]  Unit tests for lowering from Bloqade-IR to Emulator-IR
- [ ] Unit tests for lowering from Emulator-IR to RydbergHamiltonian
- [ ] integration tests to validate the correctness of the solutions generated by the entire pipeline.
