### ISSUE TITLE
Make Initialization for Multi-qubit Rabi Oscillation example

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#349]
actually, this can be simpler,

```python
geometries = [Chain(1), Chain(2), Triangular(3), Square(4), Rectangle(2, 3).add_position(0, 1.5)]
seq = start.build.sequence

geometries = map(adjust_blockade, geometries)
geometries[1].apply(seq)

# or 
geometries = map(lambda x: x.rescale(distance), geometries)
```

this should also work with `ListOfPosition` because it technically rescales the coordinates. You only need a correct `distance` parameter to adjust the atom within blockade either manually (the later) or automatically.

Note: `Rectangle(2, 3).add_position(0, 1.5)` returns a `ListOfPosition` instead of a `BoundedBravais`

_Originally posted by @Roger-luo in https://github.com/Happy-Diode/bloqade-python/pull/162#discussion_r1216999088_

**Comment by johnzl-777** [comment]
This seems to be partially correct. If you do `Triangular(3)` you'll get much more than three atoms and I don't think doing `Rectangular(2, 3).add_position(0, 1.5)` gives the correct idea, even with scaling. 

I think it might be best to mix list of coordinates with pre-defined lattice types when it's possible:

```
def rabi_ahs_program(n_atoms):

    spacing = 4.0 

    geometries = \
    { 1: Chain(1), 
      2: Chain(2, spacing), 
      3: start.add_positions(...)
      4: Square(2, spacing), 
      7: start.add_positions(...)
    }
    if n_atoms not in geometries:
        raise ValueError("natoms must be 1,2,3,4, or 7")

    prog_start = geometries[n_atoms]
    # start building the program on top of user-selected number atoms
    prog_start.rydberg.....

```

**Comment by Roger-luo** [comment]
yeah a list of pre-defined geometries makes sense to me, you prob don't need to handle the error in the examples
