### ISSUE TITLE
Fancier README

### ISSUE THREAD

**Issue by weinbe58** [QuEraComputing/bloqade-python#540]
Add things like images or code output to keep people engaged.

**Comment by johnzl-777** [comment]
Just my two cents on things I think are worth adding
* There will probably be some confusion over Bloqade.jl vs bloqade-python to newcomers of the QuEra ecosystem. I think it's worth having a paragraph or some additional information emphasizing that Bloqade.jl is *emulation* first and bloqade-python is *hardware* first
* variable assignment and local detuning should have explicit code examples, not just mentions in the text
* The pretty printing output is worth showing AND explaining (e.g. what does "Batch params/assign" mean? What about static assign/flatten params? That along with encouraging users to keep an eye on the output as a nice way to verify program correctness while they build.
* We can be explicit about the fact that while `.` separates parts of the program:
  1. It's not something inherent to our SDK, it's just the standard python attribute accessing syntax. 
  2. You're encouraged to split your program considering each step of the builder spits out an immutable object. There's nothing forcing (or even encouraging users) to write gigantic one-liners AND this has the added benefit of letting you create a "base" program object you can then build variants off of (e.g. you want to preserve a geometry but have different programs for different pulse sequences)

As well as some open questions:
* How detailed should this README be? Right now it seems rather dense but this can be ameliorated if some of my suggestions above are implemented
* What about background knowledge? Could we give a brief overview (a paragraph or two) of what we mean by drives and detunings? Or do we do what we do with Bloqade.jl's README and after installation instructions we immediately direct folks to the separate docs site?
