### ISSUE TITLE
Can't pip install bloqade-python

### ISSUE THREAD

**Issue by bsiegelwax** [QuEraComputing/bloqade-python#560]
`No matching distribution found.`

My local version is Python 3.10.9. I received the same error using the qBraid platform.

**Comment by weinbe58** [comment]
I just added support for python 3.9 I will release that version this aternoon.

**Comment by weinbe58** [comment]
@bsiegelwax Can you try installing bloqade again?

**Comment by bsiegelwax** [comment]
In qBraid and locally:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from bloqade import start
      3 calculation = (
      4     start
      5 )

ModuleNotFoundError: No module named 'bloqade'
```

It seems to be working in Google Colab, but that doesn't help me access Aquila since I use qBraid to access Aquila.

**Comment by weinbe58** [comment]
Currently its not added to the braket environment qBraid so you will need to install it yourself until we get them to add it. I was able to do this in the morning today.

**Comment by kaihsin** [comment]
Also I am not sure we tested on 32bit python.  on Google Colab free version sometimes they assign you 32bit cpu instead of 64bit

**Comment by bsiegelwax** [comment]
Some sample code just ran without errors in Colab, so I can start tinkering with bloqade-python. For execution on Aquila maybe the qBraid SDK is an option from there.

**Comment by bsiegelwax** [comment]
This ticket shouldn't be closed. Bloqade still has installation issues.
