### ISSUE TITLE
maybe just use beartype's multiple dispatch?

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#600]
maybe just use beartype's multiple dispatch?

_Originally posted by @Roger-luo in https://github.com/QuEraComputing/bloqade-python/pull/591#discussion_r1330658589_

**Comment by weinbe58** [comment]
This actually would be great, we can support both a list of dictionaries and a dictionary of lists for the `assign` and `batch_assign`.
