### ISSUE TITLE
Feature Request: Arbitrary order for Pragmas.

### ISSUE THREAD

**Issue by jon-wurtz** [QuEraComputing/bloqade-python#608]
When running `program.braket.aquila().assign(time=1)`

**Comment by weinbe58** [comment]
This is intentional, is there any reason why you would need to have the order swapped?

**Comment by weinbe58** [comment]
@jon-wurtz can you please give an example as to why you would need to swap the order of the assignment and the backend selection? Also can you please follow the format of the templates.

**Comment by jon-wurtz** [comment]
For example, if I want to feed the program into a larger pipeline, but I want the rest of the pipeline to be agnostic of the back end. In which case, I will need to feed the object with unassigned values into that pipeline.

Even better would be to combine with parallelizing, eg
```
executable = program.parallelize( ... ) .braket.aquila()

def something_to_run(executable, **kwars):
    out = executable.assign( **kwargs )
    return evaluate_function(out)
```

**Comment by weinbe58** [comment]
use `flatten` and pass the arguments into `run` method.
