### ISSUE TITLE
Rename `flatten` for clarity

### ISSUE THREAD

**Issue by weinbe58** [QuEraComputing/bloqade-python#617]
**Is your feature request related to a problem? Please describe.**
`flatten` is not intuitive; we should rename it.

**Describe the solution you'd like**
Something like `runtime_assign` makes it very clear that you are deferring the assignment of these particular variables until the task is about to be run. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Roger-luo** [comment]
do we have other things that can be deferred to runtime?

**Comment by weinbe58** [comment]
The only thing I can think of is `parallelize,` but this already has a separate method.

**Comment by weinbe58** [comment]
Actually, I think we should call it `.args([...])` because we denote those as `args` when calling `run`/`run_async`.

**Comment by Roger-luo** [comment]
I like `args` better

**Comment by weinbe58** [comment]
I think this should address the feature requested in issue #608
