### ISSUE TITLE
Establish Documentation Standards

### ISSUE THREAD

**Issue by johnzl-777** [QuEraComputing/bloqade-python#625]
**Describe the issue**

I'd like to take the time to beef up the documentation of Bloqade (I believe this would also work in favor of @weinbe58 's goal to familiarize me with more parts of the codebase 😄 ) on both the builder and underlying IR.

While we do have some fantastic docstrings for the builder (courtesy of @kaihsin 's phenomenal work!) There are some minor issues with the formatting I believe can be fixed with some small changes (see below under "Suggested Content").

I also think it would be worth picking a docstring standard for the classes beneath the builder. It makes sense we'd want an exception for standard formatting on the builder side because one of our core features is smart documentation but outside that there should be some standard.

**Link to the page and section containing the issue, if applicable**

See how nothing appears after "Possible Next": https://queracomputing.github.io/bloqade-python/latest/reference/bloqade/#bloqade.start , due to the use of angular brackets which probably makes Markdown think they're some kind of HTML tag.

https://queracomputing.github.io/bloqade-python/latest/reference/bloqade/ir/control/waveform/#bloqade.ir.control.waveform.Smooth and many other pages in our docs show we do *have* documentation but I believe it would behoove us to be more thorough/have more examples embedded in docstrings.

**Suggested content or correction, if applicable**

PEP 257 seems common but there are [other styles](https://www.datacamp.com/tutorial/docstrings-python) we could choose from. 

As for builder docstrings:
* I think it best to drop the angular brakets and just escape node names via backticks
* The choice of two colons after a bullet to separate code and text (e.g. `code.here`::lorem ipsum) I think would be a little more readable (and potentially less fragile in terms of rendering by other engines/tools) if it was just broken into nested bullets:
```
* `some code here`
  * additional text here
```
* In general the use of characters like `->` and `::` could be avoided and just substituted with standard markdown syntax. I understand it's a bit pedantic but I am just looking to ensure visual consistency in both raw markdown, mkdocs, and whatever else may try to render the docstrings.

For example, my take on `start` would be:

```
"""
    - Program starting node (equivalently achievable by choosing a lattice geometry from `bloqade.atom_arrangement`).
    - Next possible nodes:`LevelCoupling`, `AtomArrangement`

    - For `LevelCoupling` you can do either:
        - `start.rydberg`:
            To address Rydberg level coupling
        - `start.hyperfine`: 
            To address Hyperfine level coupling

    - For `AtomArrangement` you can do either:
        - `start.add_locations(List[Tuple[int]])`:
            To add multiple atoms to current register
        - `start.add_location(Tuple[int])`
            To add a single atom to the current register
"""
```

Which currently is:

```
"""
    - Program starting node
    - Possible Next <LevelCoupling>

        -> `start.rydberg`
            :: address rydberg level coupling

        -> `start.hyperfine`
            :: address hyperfine level coupling

    - Possible Next <AtomArragement>

        -> `start.add_locations(List[Tuple[int]])`
            :: add multiple atoms to current register

        -> `start.add_location(Tuple[int])`
            :: add atom to current register
"""
```

**Comment by Roger-luo** [comment]
I only have one comment: the docstring needs to be in markdown format instead of reStructuredText, our pipeline requires that to render and it's also a more popular format among developers. I don't want to increase the bar of contributing by asking for a different format. 

I don't think there is any style guide for markdown that exists in the Python world. So we should just follow our own style guide (preferably a markdown version of the Google style guide)

**Comment by kaihsin** [comment]
Just a note, I originally try to follow google style, but the rendering in
VScode looks different than on actual generated doc on website, especially
hyperlink to classes/functions via mkdoc extensions [`xxx`][bloqade.xxx]
will not looks great on VScode prompt.

**Comment by johnzl-777** [comment]
I do notice the issue with the mkdocs hyperlinks but I think it's worth it. My idea is to do the mkdocs links the *first* time something is mentioned but not subsequent times. 

e.g.
```
- blah blah blah [stuff][bloqade.stuff.stuff]
- blah blah stuff (no linking here)
```

I think this preserves the best of both worlds without being too obnoxious to folks on either side (IDE/Terminal vs. consulting mkdocs)
