### ISSUE TITLE
Let .location accept lists

### ISSUE THREAD

**Issue by johnzl-777** [QuEraComputing/bloqade-python#635]
**Is your feature request related to a problem? Please describe.**
I had a discussion with @MilanKornjacaQ who pointed out it would be desirable to have the ability to specify multiple locations for a spatial modulation at once instead of having to chain `.locations`

**Describe the solution you'd like**

Instead of `...rydberg.location(1).location(5).location(7)` a user could just do:
`...rydberg.location([1,5,7])`

**Describe alternatives you've considered**

You can do this with the `.var` attribute as you build your program but it seems to me to be somewhat awkward to force users into having to use a variable when they're not interested in a parameterized program. 

**Additional context**

**Comment by weinbe58** [comment]
I think a better api is to use a single method call for `location` because it can greatly compact the syntax:

`...location(1).scale(2).location(0).scale("a").location(3)` condenses to `location([1,0,3],[2,"a",1])`

**Comment by MilanKornjacaQ** [comment]
> I think a better api is to use a single method call for `location` because it can greatly compact the syntax:
> 
> `...location(1).scale(2).location(0).scale("a").location(3)` condenses to `location([1,0,3],[2,"a",1])`
> 
> Also if you do not specify the second argument it defaults to `1` for each location in the list.

This is exactly the functionality I would like, as the location-scale chain is tedious. Didn't know it's already there.
