### ISSUE TITLE
Builder printing is broken. 

### ISSUE THREAD

**Issue by weinbe58** [QuEraComputing/bloqade-python#650]
**Describe the bug**
ipython the builder doesn't show because of some old code that needs to be deleted. 

**Minimal broken example**
`prog = start.rydberg.detuning` will not work in ipython

**Desktop (please complete the following information):**
 - OS: OS-X
 - Bloqade Version: 0.5.1
 - Python Version: 3.11

**Comment by weinbe58** [comment]
I can't reproduce this @johnzl-777 can you make sure your version of bloqade is up to date?

**Comment by johnzl-777** [comment]
Updated my `venv` to be on the same Bloqade version. The code snippet you have works but the moment I hit `uniform` afterwards the next steps aren't there.

I think this is just because we're missing the proper type hints.

**Comment by weinbe58** [comment]
if the printing works I'm gonna close this issue and we can take the other issue with the type hints over to the new issues I created.
