### ISSUE TITLE
Incomplete Tutorials

### ISSUE THREAD

**Issue by dancbeaulieu** [QuEraComputing/bloqade-python#676]
**Describe the issue**
The tutorials often refer to a file that doesn't exist, such as [Solving the Maximal Independent Set Problem on defective King Graph](https://queracomputing.github.io/bloqade-python-examples/latest/examples/example-5-MIS-UDG/) having a line that accesses a "MIS-UDG-job.json" file that isn't linked in the example. Quantum SCAR also has a similar issue with "quantum-scar-dynamics-emulation.json". 

**Link to the page and section containing the issue, if applicable**
[Solving the Maximal Independent Set Problem on Defective King Graph](https://queracomputing.github.io/bloqade-python-examples/latest/examples/example-5-MIS-UDG/))

**Suggested content or correction, if applicable**
Either these should be accessible or you should change the source datasets. Tutorials should be able to successfully run on users computer so they can play with the techniques.

**Comment by weinbe58** [comment]
Thanks for you feedback! 

That's a good idea to make that file available. To the point of making the examples run, you just need to create a `data` directory in your CWD for the python interpreter/kernel that is running. We can add some code that automatically creates this directory which would probably be nice to ensure they run without this step.

**Comment by Roger-luo** [comment]
hmm, shouldn't this be automatic? creating `data` dir sounds too much boilerplate to me.

**Comment by weinbe58** [comment]
@johnzl-777 Add links to download the json files.

**Comment by weinbe58** [comment]
Tutorials now have download for the script as well as the QPU data.
