### ISSUE TITLE
doc edit link is broken

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#690]
the edit link is broken, e.g the link points to `master` branch

<img width="807" alt="image" src="https://github.com/QuEraComputing/bloqade-python/assets/8445510/ffbfc2a1-bd67-4601-8728-416bad447723">

it's not clear to me why this is the case, how do we have the `master` branch at all?

**Comment by weinbe58** [comment]
There is no `master` branch so this is quite odd.

**Comment by weinbe58** [comment]
Yeah its because of a default setting in mkdocs https://www.mkdocs.org/user-guide/configuration/

>Warning
>
>On GitHub and GitLab, the default "edit" path (edit/master/docs/) opens the page in the online editor.

**Comment by weinbe58** [comment]
I think part of the issue is that we do not have our documentation set up on a standard configurations, e.g., we have a separate `docs` directory which breaks the links when mkdocs tries to set the edit link to source code. 

I think we need to rearrange the file structure to make this work.
