### ISSUE TITLE
deserialize json

### ISSUE THREAD

**Issue by jon-wurtz** [QuEraComputing/bloqade-python#696]
**Is your feature request related to a problem? Please describe.**
Let the user handle further downstream serialization and deserialization of tasks

**Describe the solution you'd like**
```
job2 = bloqade.deserialize(job.json())
```

**Describe alternatives you've considered**
Simply use the `bloqade.load()` object but this only accepts filenames and a very particular IO class type

**Additional context**

**Comment by weinbe58** [comment]
use `loads`/`dumps` if you want JSON strings.

**Comment by jon-wurtz** [comment]
https://queracomputing.github.io/bloqade-python/latest/reference/bloqade/serialize/ 👍
