### ISSUE TITLE
Appending pieces of dynamics together

### ISSUE THREAD

**Issue by jon-wurtz** [QuEraComputing/bloqade-python#697]
**Is your feature request related to a problem? Please describe.**
Implementing sequential execution of different analog programs. So for example, for the first 1usec one does state prep, and for the second 3usec one does a quench.

**Describe the solution you'd like**
```
job1 = start.add_location().rydberg.piecewise_linear(). ... ...
job2 = start.add_location().rydberg.piecewise_linear(). ... ...

total_job = bloqade.append(job1,job2)
```
**Describe alternatives you've considered**
Appending together at the waveform IR level (yuck)

**Comment by weinbe58** [comment]
We already have an example on how to do this, please go through the [scar example](https://queracomputing.github.io/bloqade-python-examples/latest/examples/example-4-quantum-scar-dynamics/#define-the-program)where we basically build sequences and append them together.

**Comment by jon-wurtz** [comment]
This is too abstract, hard to understand, and not easily composable. My feature request of (more or less) an `append` function still stands...
```
(
    Chain(n_atoms, lattice_spacing=atom_spacing)
    # define detuning waveform
    .rydberg.detuning.uniform.piecewise_linear(
        [0.3, 1.6, 0.3], [-18.8, -18.8, 16.3, 16.3]
    )
    .piecewise_linear([0.2, 1.6], [16.3, 0.0, 0.0])
    # slice the detuning waveform
    .slice(start=0, stop=run_time)
    # define rabi waveform
    .amplitude.uniform.piecewise_linear([0.3, 1.6, 0.3], [0.0, 15.7, 15.7, 0.0])
    .piecewise_linear([0.2, 1.4, 0.2], [0, 15.7, 15.7, 0])
    # slice waveform, add padding for the linear segment
    .slice(start=0, stop=run_time - 0.065)
    # record the value of the waveform at the end of the slice to "rabi_value"
    .record("rabi_value")
    # append segment to waveform that fixes the value of the waveform to 0
    # at the end of the waveform
    .linear("rabi_value", 0, 0.065)
)
```

**Comment by weinbe58** [comment]
OK, but this isn't a blocker. You can compose pieces together. It is just inconvenient to have to copy and paste code. I will put this into the backlog because we have other priorities to focus on now.

**Comment by weinbe58** [comment]
Upon further thought, I think we should support this going forward. I have some ideas on how to support the full IR for both hardware and emulation.
