### ISSUE TITLE
 cannot import name 'save_batch'

### ISSUE THREAD

**Issue by balewski** [QuEraComputing/bloqade-python#704]
**Describe the bug**
save_batch module is missing
**Minimal broken example**
$ python3 -c 'from bloqade import start, save_batch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'save_batch' from 'bloqade' (/usr/local/lib/python3.10/dist-packages/bloqade/__init__.py)
**Expected behavior**
no error
**Desktop (please complete the following information):**
 - OS: Ubuntu22
 - pip3 list |grep bloq
bloqade                         0.7.0
$ python3 -V
Python 3.10.12

**Comment by weinbe58** [comment]
Hi @balewski unfortunately we've deprecated those functions for a new interface `load` and `save`. https://github.com/QuEraComputing/bloqade-python/pull/589

If you have any old files that were saved in the old format I can provide a script that will convert them to the new format.

**Comment by balewski** [comment]
Hi Philip,
I see. I have no old data to  read-in.  I'm just starting my Bloquade-python education.
You may correct your 'phylosophy' page, so all what is there runs. 
There are also few typos in the code stubs, e.g. there is a missing coma here: 
￼
You can close this ticket
Thanks
Jan

**Comment by weinbe58** [comment]
Oh, hi, Jan! Yes I will be working on the documentation in the coming weeks so I appreciate your feedback
