### ISSUE TITLE
404 error for the reference and License page

### ISSUE THREAD

**Issue by Wang-Shengtao** [QuEraComputing/bloqade-python#718]
**Describe the issue**
When I'm in the tutorials page on documentation and then click reference tab or license tab, a 404 error will appear. If I start with other pages (home, getting started, etc.), it doesn't seem to have issues. 

**Link to the page and section containing the issue, if applicable**
https://queracomputing.github.io/bloqade-python-examples/latest/

**Comment by weinbe58** [comment]
changes should be up in in a 10 minutes or so.
