### ISSUE TITLE
Improve documentation on Batch tasks. 

### ISSUE THREAD

**Issue by weinbe58** [QuEraComputing/bloqade-python#741]
- [ ] Document `QuEraTaskStatus` Enum and link that docs in `RemoteBatch` documentation. 
- [ ] Improve documentation on `LocalBatch` and `RemoteBatch`

bounty: 20 USD

**Comment by WingCode** [comment]
Could I be assigned to this issue for the UH bots?

**Comment by Roger-luo** [comment]
apologies, I forgot about this one. Please see https://github.com/unitaryfund/unitaryHACK2024/pull/23/files
