### ISSUE TITLE
Hardware Capabilities in Documentation

### ISSUE THREAD

**Issue by johnzl-777** [QuEraComputing/bloqade-python#743]
**Describe the issue**

Credit to @plquera for this one, this would be a follow up to #724 where the docs also show hardware capabilities info

**Link to the page and section containing the issue, if applicable**

**Suggested content or correction, if applicable**

<img width="294" alt="Screenshot 2023-10-24 at 9 18 14 AM" src="https://github.com/QuEraComputing/bloqade-python/assets/32608115/e47c01c0-edd4-4e7e-8447-53c8f9f9eebe">

Perhaps a "Hardware Reference" Section would be helpful around the API Reference section that would just mirror the data from https://queracomputing.github.io/Bloqade.jl/dev/capabilities/ along with mentioning the existing API we have for getting hardware  capabilities

### Tasks
------

- [ ]  #737 
- [ ] #745

**Comment by weinbe58** [comment]
The API reference is for the package we should probably have a separate section on the website for hardware unless we specifically add a module in bloqade called `hardware`.

**Comment by weinbe58** [comment]
I would suggest we first add issue #737 first and add the documentation about the meaning of the capabilities to the doc string of `get_capabilities` since that is the only function that actually has anything to do with hardware.
