### ISSUE TITLE
Visualization states variable is missing assignment when assignment is present

### ISSUE THREAD

**Issue by johnzl-777** [QuEraComputing/bloqade-python#747]
**Describe the bug**

@plquera was experimenting with the following program:
```python
durations = cast([0.1,"sweep_time",0.1])
total_time = sum(durations)

@waveform(total_time)
def detuning(time, det_frequency, det_amplitude):
    return -det_amplitude * np.sin(det_frequency * time)


pwl_detuning = detuning.sample(0.05, "linear")
pwl_amplitude = piecewise_linear(durations, [0,15.7,15.7,0])


program = rydberg_h(
    [(0, 0), (0,"r")],
    detuning=pwl_detuning,
    amplitude= pwl_amplitude,
    static_params={"det_frequency":1, "det_amplitude":1.5, "sweep_time":3.8},
    batch_params=[dict(r=r) for r in [6.0, 7.0, 10.0]],
)
```

And upon attempting to perform `program.show()` an error was returned that `sweep_time` did not have a definition despite one being present. 

The program is syntactically correct and runs successfully in emulation, meaning this must be restricted to visualization. 

**Minimal broken example**

**Expected behavior**

The user should be able to see everything plotted with all variables having a proper assignment.

**Screenshots**

**Desktop (please complete the following information):**
 - Bloqade Version:
 - Python Version:

**Additional context**

**Comment by weinbe58** [comment]
`program` is a Routine which doesn't implement `show`

**Comment by johnzl-777** [comment]
Ah would it be possible to have an error message that catches this via type versus saying the more confusing "this variable isn't assigned"? Or will this problem go alway altogether with the completion of #746

**Comment by weinbe58** [comment]
it should go away with #746 because with your example if you do `program.source.show()` it works and `program.source` is a builder.

**Comment by weinbe58** [comment]
> Ah would it be possible to have an error message that catches this via type versus saying the more confusing "this variable isn't assigned"? Or will this problem go alway altogether with the completion of #746

I am working on some tools to do the assignment analysis on the IR which should be merge in probably in a week or so.
