### ISSUE TITLE
More Programmatic `rydberg_h`

### ISSUE THREAD

**Issue by johnzl-777** [QuEraComputing/bloqade-python#752]
**Is your feature request related to a problem? Please describe.**

Revisiting a snippet from @plquera 's program:

```python
program = rydberg_h(
    [(0, 0), (0,"r")],
    detuning=pwl_detuning,
    amplitude= pwl_amplitude,
    static_params={"det_frequency":1, "det_amplitude":1.5, "sweep_time":3.8},
    batch_params=[dict(r=r) for r in [6.0, 7.0, 10.0]],
)
```
It seems it would be more convenient and intuitive for users if they could just do:
`batch_params = [{"r":[6.0, 7.0, 10.0]}` and arguably more programmatic considering we encourage this style over creating individual small dictionaries for the same parameter to have different values when using the standard builder syntax.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by weinbe58** [comment]
you can do this but you either have to have a dictionary of lists or a list of dictionaries

for your example the following are both correct:

```python
program = rydberg_h(
    [(0, 0), (0,"r")],
    detuning=pwl_detuning,
    amplitude= pwl_amplitude,
    static_params=dict(det_frequency=1, det_amplitude=1.5, sweep_time=3.8),
    batch_params=dict(r=[0.1,0.2,0.3]),
)

program = rydberg_h(
    [(0, 0), (0,"r")],
    detuning=pwl_detuning,
    amplitude= pwl_amplitude,
    static_params=dict(det_frequency=1, det_amplitude=1.5, sweep_time=3.8),
    batch_params=[dict(r=r) for r in [0.1,0.2,0.3]],
)

```
