### ISSUE TITLE
no reinitialization of task.backend after deserialization

### ISSUE THREAD

**Issue by jon-wurtz** [QuEraComputing/bloqade-python#755]
**Describe the bug**
When deserializing a task submitted through a QuEra internal queue (non-AWS), the `task.backend` object is a dictionary and not an object.

**Minimal broken example**
1. Submit a task through QuEra internal queue
2. Serialize that submitted task to file.
3. Deserialize that submitted task from file
4. Call task.pull()
5. This will call an `AttributeError: 'dict' object has no attribute 'task_results'`

**Expected behavior**
Task.pull() runs successfully and the backend is correctly initialized

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Bloqade Version: 0.4.5
 - Python Version: 3.11.4

**Comment by weinbe58** [comment]
Fixed in #754
