### ISSUE TITLE
align on best practices and common gotchas

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#757]
I notice we recently have a lot of use cases arising and people may choose their way to implement things. However, these implementation does not always align well with the design intention, it is important to point out and collect best practice through issue reports instead of burying them in the history. 

So ideally there should be a section/page in our documentation titled "Best Practices & Common Gotchas" with subsections like our tutorial but instead pointing out what's the best practice for doing X.

for example some of the reports I see from recent issues #752 and using `copy` on builders, not using variables but assigning manually etc.

**Comment by johnzl-777** [comment]
I like this idea a lot, I think it would be a great way to encourage users to fully leverage the capabilities that Bloqade has to offer and avoid a lot of duplicated work (which I've witnessed first hand in users recreating a lot of structures that Bloqade directly offers).

If there's interest in this I could draft something up but I can wait until after triage too.

**Comment by Roger-luo** [comment]
another idea, we can give issues that may not using best practice a "gotcha" tag to categorize this type of issues.

**Comment by Roger-luo** [comment]
another reference for quick start & best practice https://configurations.rogerluo.dev/stable/quick-start/

**Comment by weinbe58** [comment]
We've started this process we just need to keep on updating the page as we go.
