### ISSUE TITLE
Add ability to cite bloqade-python

### ISSUE THREAD

**Issue by johnzl-777** [QuEraComputing/bloqade-python#877]
**Is your feature request related to a problem? Please describe.**
There currently isn't a standard way to cite bloqade-python in literature

**Describe the solution you'd like**
There should be a "Citation" section like the one in Bloqade.jl (see [here](https://github.com/QuEraComputing/Bloqade.jl?tab=readme-ov-file#citation))

**Comment by Roger-luo** [comment]
I think we should consider writing a white paper this year as this is going/has to be mature this year.  @weinbe58 @Wang-Shengtao

**Comment by johnzl-777** [comment]
@MilanKornjacaQ is also requesting this

**Comment by Roger-luo** [comment]
for now, I think it should stay the same as Bloqade.jl - just use the similar bibtex with a different link. But we should write a short paper despite of what journal, to make things appear on google scholar etc.

**Comment by MilanKornjacaQ** [comment]
I want to cite both as I use them for different purposes and want to give proper credit; I guess both for Bloqade.jl and bloqade-python, I suggest you think about getting a DOI so that citations can be tracked.

**Comment by Roger-luo** [comment]
>  I suggest you think about getting a DOI so that citations can be tracked.

Yes, I think having a short paper covering both would be nice, which would give us both DOI and some exposure. But I just enabled zonodo. If we have no objections, I can generate a DOI with that.

**Comment by Roger-luo** [comment]
ok done. please see README and the citation button.
