### ISSUE TITLE
Bloqade logo not rendering on PyPI

### ISSUE THREAD

**Issue by ryanhill1** [QuEraComputing/bloqade-python#913]
Low priority issue, but thought I would bring to your attention that the Bloqade logo isn't rendering on the PyPI page:

<img width="1205" alt="Screenshot 2024-03-04 at 8 02 21 PM" src="https://github.com/QuEraComputing/bloqade-python/assets/46977852/6565f2ba-4c32-463a-baad-ef7697060b48">

**Comment by weinbe58** [comment]
This is probably due to the html in the README that is used to switch between the dark and light theme logo.
