### ISSUE TITLE
unitaryhack tracking issue for @shubhusion

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#986]
by @shubhusion 

- https://github.com/QuEraComputing/bloqade-python/pull/965 20 USD
- https://github.com/QuEraComputing/bloqade-python/pull/966 20 USD

total 40 USD

**Comment by shubhusion** [comment]
@Roger-luo can you assign this issue to me ? Due to not assigning my name is not in the Unitaryhack leaderboard yet.
