### ISSUE TITLE
unitary hack tracking issue for qmanning4

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#988]
done by @qmanning4:

- https://github.com/QuEraComputing/bloqade-python-examples/pull/72 USD 20

total 20 USD

**Comment by Roger-luo** [comment]
@qmanning4 please reply in this thread so I can assign the issue to you. Thank you!

**Comment by qmanning4** [comment]
👋 I'm here. Thanks Roger!
